swagger: '2.0'
info:
  title: "ID_Quilmes"
  version: "20210318191249"
host: localhost:8080
schemes:
  - http
basePath: /ID_QuilmesJavaEnvironment/holaMundo
produces:
  - application/json
paths:
  /saludo:
    get:
      tags:
        - holaMundo  
      operationId: "saludo"
      summary: "saludo"
      responses:
        200:
          description: "Successful operation"
            type: "string"

        404:
          description: "Not found"

definitions:
  saludoOutput:
    properties:
      Mensaje:
        type: "string"


  
